### ISSUE TITLE
Glow

### ISSUE THREAD

**Issue by KKriebel** [ElijahPepe/BDThemes#1]
A couple things
1. The "glowing" aspect doesn't work 
2. The background is transparent not solid
3. The link to the discord has expired on the BetterDiscord page.

**Comment by ElijahPepe** [comment]
So, apologies for the glow aspect, I put that in as post-FX but since people really like it I'm working on making it into the actual CSS.

As for 2, the background is designed to be black and only black as to imitate it as much as possible. I've fixed #3 though.

**EDIT:** Got your message about the background on BDL. I'll try to make that an addon as well.

**Comment by ElijahPepe** [comment]
ETA for glow is this week.

**Comment by KKriebel** [comment]
Thank you!

Sincerely,
K. Kriebel
